In [1]:
import pandas as pd

In [2]:
Data_IL = pd.read_csv('./Data/Data_weathersample.csv')
Data_IL

,year,Loss,pcpn1,pcpn2,pcpn3,pcpn4,pcpn5,pcpn6,pcpn7,pcpn8,...,vpdmin3,vpdmin4,vpdmin5,vpdmin6,vpdmin7,vpdmin8,vpdmin9,vpdmin10,vpdmin11,vpdmin12
0,1942,267.090228,15.273145,97.870036,51.364842,90.998884,130.080919,149.213821,133.597300,73.390518,...,1.219106,2.038690,1.814711,1.775482,2.276900,1.258415,1.226865,1.312048,0.903694,0.762198
1,1975,291.581189,52.950681,78.469783,57.016809,95.068405,138.041628,113.398004,24.892235,106.318135,...,0.795685,1.479532,2.710359,3.273770,3.697857,3.419566,2.028563,2.244638,1.177374,0.606591
2,1953,328.710496,27.685939,31.485501,98.355327,63.623128,59.135198,77.187604,46.797126,33.184020,...,0.496551,1.077729,1.674200,3.315411,2.531723,3.223090,3.733153,2.285155,1.128360,0.325958
3,1969,325.175460,93.095109,52.111971,54.682743,107.746889,85.340909,156.307351,200.219568,40.313236,...,0.806261,1.368742,1.593452,1.576465,1.689301,1.328530,1.238523,1.306215,0.809886,0.720025
4,1970,313.945595,9.970054,9.225498,52.230733,157.064311,172.948936,128.713133,66.635172,270.386257,...,0.907358,1.542496,1.994325,1.319503,2.537332,1.539028,1.063301,1.399159,0.712257,0.542998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1992,184.256917,24.010979,35.946860,54.138525,40.149313,7.710484,43.992199,260.923427,33.030833,...,0.454061,0.658021,1.638236,1.903250,0.177887,0.469776,0.473763,0.521296,0.223975,0.305344
996,2007,166.764295,71.403971,58.859971,151.655392,95.639661,62.551810,96.606249,89.838158,141.503367,...,0.412380,1.031550,2.642745,1.665835,1.169015,1.152770,1.651840,1.149820,0.566315,0.291645
997,2016,166.630148,15.599644,19.573762,64.387616,39.189247,100.093459,84.385655,149.770598,200.580466,...,0.692987,1.154894,1.262128,2.020144,0.737265,0.496764,0.684832,0.485096,0.673723,0.279486
998,2004,185.537906,18.610789,12.646899,91.527724,48.562596,156.175090,66.815782,62.779169,114.159717,...,0.724331,1.672487,1.333254,1.010784,0.879011,0.429277,0.664103,0.361581,0.281383,0.245451
999,2014,177.473239,47.791691,65.667950,41.126033,97.065363,74.053287,182.283426,75.645896,148.039930,...,0.538109,1.351912,1.681678,1.335519,1.202260,0.893056,0.870868,0.575538,0.670686,0.326254

In [3]:
Data_IL[Data_IL['year'] >= 1925][Data_IL['year'] <= 1991]

,year,Loss,pcpn1,pcpn2,pcpn3,pcpn4,pcpn5,pcpn6,pcpn7,pcpn8,...,vpdmin3,vpdmin4,vpdmin5,vpdmin6,vpdmin7,vpdmin8,vpdmin9,vpdmin10,vpdmin11,vpdmin12
0,1942,267.090228,15.273145,97.870036,51.364842,90.998884,130.080919,149.213821,133.597300,73.390518,...,1.219106,2.038690,1.814711,1.775482,2.276900,1.258415,1.226865,1.312048,0.903694,0.762198
1,1975,291.581189,52.950681,78.469783,57.016809,95.068405,138.041628,113.398004,24.892235,106.318135,...,0.795685,1.479532,2.710359,3.273770,3.697857,3.419566,2.028563,2.244638,1.177374,0.606591
2,1953,328.710496,27.685939,31.485501,98.355327,63.623128,59.135198,77.187604,46.797126,33.184020,...,0.496551,1.077729,1.674200,3.315411,2.531723,3.223090,3.733153,2.285155,1.128360,0.325958
3,1969,325.175460,93.095109,52.111971,54.682743,107.746889,85.340909,156.307351,200.219568,40.313236,...,0.806261,1.368742,1.593452,1.576465,1.689301,1.328530,1.238523,1.306215,0.809886,0.720025
4,1970,313.945595,9.970054,9.225498,52.230733,157.064311,172.948936,128.713133,66.635172,270.386257,...,0.907358,1.542496,1.994325,1.319503,2.537332,1.539028,1.063301,1.399159,0.712257,0.542998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,1954,201.856190,30.718542,55.778809,102.094406,125.602339,81.448619,106.055286,91.559523,145.327957,...,0.605115,1.356580,1.506609,2.584268,2.069073,0.342229,1.882110,0.708543,0.837942,0.423343
990,1928,161.607889,17.295966,45.007407,32.562210,67.359561,55.158334,132.418177,92.723169,81.678178,...,0.908189,1.279859,1.747232,1.026634,1.280978,0.995014,0.868748,0.899640,0.848912,0.618743
991,1961,181.828832,8.594232,26.738619,83.988999,66.275391,65.065408,61.906941,130.871456,60.571813,...,0.432462,0.686423,1.676408,2.262354,1.280798,1.117258,1.093270,0.742683,0.576929,0.503066
992,1935,186.905489,51.736187,55.694524,92.955773,62.154776,185.458982,138.859583,90.589547,58.936051,...,1.110156,1.248423,1.002005,1.296951,1.911057,0.940137,1.147747,1.062571,0.859273,0.611283
993,1974,274.848474,78.879700,47.359201,80.804969,97.027379,164.787134,200.742773,47.892675,39.998201,...,0.838110,1.996608,1.555800,1.975280,2.935880,1.316271,1.096000,1.434589,0.613172,0.305541

In [4]:
data_train = Data_IL[(Data_IL['year'] >= 1925)][(Data_IL['year'] <= 1991)]
data_train.head()

,year,Loss,pcpn1,pcpn2,pcpn3,pcpn4,pcpn5,pcpn6,pcpn7,pcpn8,...,vpdmin3,vpdmin4,vpdmin5,vpdmin6,vpdmin7,vpdmin8,vpdmin9,vpdmin10,vpdmin11,vpdmin12
0,1942,267.090228,15.273145,97.870036,51.364842,90.998884,130.080919,149.213821,133.597300,73.390518,...,1.219106,2.038690,1.814711,1.775482,2.276900,1.258415,1.226865,1.312048,0.903694,0.762198
1,1975,291.581189,52.950681,78.469783,57.016809,95.068405,138.041628,113.398004,24.892235,106.318135,...,0.795685,1.479532,2.710359,3.273770,3.697857,3.419566,2.028563,2.244638,1.177374,0.606591
2,1953,328.710496,27.685939,31.485501,98.355327,63.623128,59.135198,77.187604,46.797126,33.184020,...,0.496551,1.077729,1.674200,3.315411,2.531723,3.223090,3.733153,2.285155,1.128360,0.325958
3,1969,325.175460,93.095109,52.111971,54.682743,107.746889,85.340909,156.307351,200.219568,40.313236,...,0.806261,1.368742,1.593452,1.576465,1.689301,1.328530,1.238523,1.306215,0.809886,0.720025
4,1970,313.945595,9.970054,9.225498,52.230733,157.064311,172.948936,128.713133,66.635172,270.386257,...,0.907358,1.542496,1.994325,1.319503,2.537332,1.539028,1.063301,1.399159,0.712257,0.542998

In [24]:

Y_train = data_train['Loss']
a = Y_train.to_numpy()

array([267.0902278 , 291.5811889 , 328.7104956 , 325.1754597 ,
       313.945595  , 314.3273807 , 224.6567526 , 296.6254739 ,
       274.2292084 , 281.2206442 , 211.6372542 , 295.8056846 ,
       245.5781552 , 232.5481101 , 413.2219952 , 386.1650553 ,
       269.8211022 , 253.6379929 , 319.7412988 , 342.624662  ,
       310.2614551 , 262.6322265 , 263.6777133 , 279.8193887 ,
       254.311202  , 274.3410903 , 291.7758229 , 259.3072225 ,
       267.9282928 , 328.1343318 , 336.8605083 , 303.8395944 ,
       325.4919678 , 305.9978645 , 312.258961  , 295.8599813 ,
       276.5142538 , 234.8426185 , 263.5119438 , 212.488049  ,
       203.5086437 , 268.8833826 , 259.3484208 , 239.689241  ,
       221.9940344 , 291.2829457 , 199.0950595 , 202.0617775 ,
       201.3302471 , 200.9529949 , 204.4576856 , 199.8587399 ,
       201.1045705 , 203.2871396 , 197.3937161 , 229.1517388 ,
       235.0323011 , 239.9893749 , 244.8949014 , 221.9784798 ,
       210.5423918 , 192.592422  , 255.5365968 , 254.1281714 ,
       252.1726149 , 152.6455313 , 254.3350267 , 193.5515428 ,
       330.910628  , 228.1972632 , 185.9759559 , 200.0670455 ,
       224.6473657 , 209.6525961 , 205.1680487 , 197.1796148 ,
       272.5659751 , 338.9678205 , 291.2822189 ,  74.96101238,
       175.2046329 , 332.7808787 , 396.4418869 , 251.4724036 ,
       372.1634541 , 391.1475282 , 367.4851806 , 451.2561078 ,
       309.2361124 , 345.7049807 , 375.1613586 , 354.4867333 ,
       336.3102146 , 329.5374474 , 335.3978218 , 341.9994447 ,
       331.5246119 , 200.9319446 , 291.192179  , 301.0917784 ,
       246.0297152 , 208.8865795 , 300.1489261 , 207.8502655 ,
       308.4292361 , 285.6893673 , 323.4551063 , 348.3828338 ,
       384.0201996 , 386.1054035 , 342.9529547 , 422.9622807 ,
       394.9686839 , 352.7635358 , 388.4562687 , 131.2109885 ,
       445.9463766 , 221.8440737 , 273.1967149 , 167.1827553 ,
       144.2952323 , 231.9467386 , 231.4895679 , 249.662702  ,
       292.5487512 , 193.1071013 , 359.6573493 , 175.8380724 ,
       216.9065702 , 181.4572265 , 190.5328016 , 233.0931617 ,
       238.4506205 , 297.9322714 , 229.9183    , 374.9101848 ,
       248.0414268 , 269.7158483 , 139.1016671 , 208.5523221 ,
       271.5540354 , 252.524045  , 199.0820454 , 194.7602561 ,
       309.5839431 , 285.749019  , 232.4927393 , 302.9138509 ,
       266.9296319 , 260.4083581 , 232.2659858 , 244.5146217 ,
       226.6252747 , 283.0606257 , 222.7818387 , 250.3710668 ,
       333.6344658 , 374.0363168 , 381.3485133 , 352.7516627 ,
       365.9021373 , 391.1725102 , 349.0780262 , 356.383025  ,
       380.8035096 , 347.0406112 , 380.6359643 , 305.0338713 ,
       337.6655523 , 238.6896799 , 280.4728289 , 301.1059265 ,
       370.3079639 , 274.7641622 , 224.5437451 , 243.0670209 ,
       228.7951015 , 286.744367  , 274.2688349 , 322.5770575 ,
       422.378973  , 401.2072773 , 387.7152718 , 486.8149959 ,
       382.9015013 , 359.9016558 , 447.2251932 , 421.547208  ,
       402.6202311 , 370.486532  , 237.3546943 , 244.5436895 ,
       254.7409089 , 267.9799881 , 297.000448  , 235.2805789 ,
       247.0806227 , 296.9876471 , 268.5994316 , 437.7910731 ,
       210.2622687 , 328.4092924 , 327.9151848 , 284.3975459 ,
       270.9401665 , 280.388479  , 277.1243548 , 278.1235866 ,
       266.1538512 , 281.3648278 , 345.3847846 , 283.2017503 ,
       244.5572104 , 217.6704035 , 317.6428046 , 198.0914132 ,
       257.515792  , 257.6759641 , 208.7667705 , 345.4707635 ,
       221.4413583 , 254.7657557 , 368.3266884 , 388.751423  ,
       314.5595633 , 549.0383758 , 210.3334752 , 259.4584647 ,
       200.0797223 , 191.3908894 , 240.9833955 , 218.0528033 ,
       186.0190159 , 177.2210336 , 245.0436402 , 198.1553449 ,
       279.8796363 , 227.5544395 , 317.2681788 , 265.2028613 ,
       199.3221377 , 177.6096381 , 206.4259009 , 333.0680076 ,
       201.5935372 , 225.5837747 , 298.9487938 , 144.9226215 ,
       164.5124792 , 222.5982977 , 224.7810524 , 194.6169469 ,
       267.8666894 , 261.6501463 , 262.1041331 , 265.9814821 ,
       268.5372917 , 265.9869093 , 267.7394354 , 264.4511365 ,
       342.4086898 , 465.6135912 , 450.9796156 , 352.6919188 ,
       321.5905896 , 369.8758245 , 331.2705013 , 373.8797378 ,
       363.1016016 , 221.6999822 , 330.1217837 , 318.1556971 ,
       392.2149708 , 407.6380892 , 328.0516955 , 250.2739713 ,
       309.8332994 , 520.5700457 , 349.944708  , 548.2036352 ,
       505.6123068 , 436.6206479 , 467.4615857 , 339.8344174 ,
       315.0125635 , 407.7351293 , 456.9307012 , 339.2917809 ,
       378.7487038 , 442.0138213 , 563.934824  , 262.4312133 ,
       258.4267506 , 275.45025   , 271.2481797 , 268.132947  ,
       263.1093335 , 263.4032769 , 264.4091821 , 347.2081944 ,
       258.4411469 , 256.9395834 , 254.6923096 , 340.3839688 ,
       253.3964282 , 234.367605  , 227.6844516 , 236.3462787 ,
       253.2676155 , 279.6199352 , 326.7656011 , 307.0024301 ,
       294.5160925 , 296.4474801 , 367.7375167 , 368.613704  ,
       235.4136888 , 225.7253229 , 219.9559842 , 190.6845714 ,
       260.2763265 , 222.9923019 , 191.9242955 , 199.7214311 ,
       185.2598595 , 191.9033833 , 182.7313156 , 197.0630451 ,
       200.4476901 , 202.3706554 , 240.9873146 , 207.8602463 ,
       224.9503704 , 208.8111664 , 199.0584531 , 193.9522916 ,
       219.2807647 , 228.4979629 , 202.6311291 , 238.9028464 ,
       223.4548199 , 361.1999681 , 349.1898437 , 359.0447819 ,
       307.830761  , 364.9596594 , 369.016913  , 399.8813281 ,
       380.0232152 , 181.3875724 , 327.2086935 , 238.1112261 ,
       239.565664  , 277.1038562 , 276.654765  , 310.927506  ,
       320.0193607 , 318.9946156 , 221.8011848 , 233.0253458 ,
       267.0217931 , 206.5325421 , 386.1152161 , 216.9243148 ,
       193.6196499 , 200.0155085 , 258.0193102 , 200.9345637 ,
       223.4286291 , 218.1324394 , 202.3875332 , 202.5524375 ,
       214.0541758 , 246.4120758 , 195.7722648 , 199.7705026 ,
       293.8404701 , 184.1464476 , 239.811276  , 223.8616101 ,
       186.8029254 , 171.6298269 , 234.9184981 , 204.4176161 ,
       166.626285  , 251.3170169 , 317.6346378 , 193.0322163 ,
       257.7057207 , 260.6612926 , 258.7949454 , 282.3287818 ,
       251.1659211 , 298.3643293 , 217.2724604 , 441.5266234 ,
       297.6294027 , 181.9101316 , 213.0446267 , 161.8601095 ,
       266.6026269 , 227.9053738 , 237.549174  , 187.5145909 ,
       192.8575988 , 184.0709604 , 188.5358672 , 184.8148364 ,
       202.503696  , 193.4771351 , 187.0637839 , 187.6296953 ,
       188.7722921 , 270.8128447 , 293.3193299 , 285.2603701 ,
       285.9552626 , 300.4180447 , 239.1587576 , 277.8214751 ,
       373.3064471 , 302.4119057 , 302.2471535 , 301.6659554 ,
       305.2002422 , 301.7694186 , 403.5233691 , 382.6087262 ,
       386.6379218 , 403.3109878 , 424.9267225 , 335.1960626 ,
       345.0366536 , 379.6787188 , 359.9097649 , 354.8771524 ,
       214.2870068 , 239.2310359 , 186.9666975 , 194.43548   ,
       184.1705811 , 173.0728282 , 255.385188  , 180.8250925 ,
       283.6715537 , 235.4999025 , 235.6692863 , 214.0358968 ,
       200.007483  , 194.6000301 , 189.4628529 , 239.1037365 ,
       227.5348267 , 413.0834651 , 291.8086349 , 167.4995992 ,
       436.0330708 , 540.0202823 , 438.2637958 , 353.8229665 ,
       375.37994   , 380.6185616 , 347.8826442 , 343.9310563 ,
       336.3148822 , 342.5255685 , 376.7599496 , 387.5383615 ,
       271.0753525 , 251.4529338 , 272.6944877 , 253.9295093 ,
       228.8124676 , 377.6600184 , 231.6352519 , 259.8361953 ,
       318.0863027 , 261.9099317 , 300.2114354 , 391.8532364 ,
       228.9829804 , 261.9194173 , 245.1653435 , 219.8529609 ,
       236.9477686 , 226.6563851 , 226.0806557 , 234.9262675 ,
       246.9008091 , 174.2551872 , 156.5761692 , 261.5224802 ,
       265.922855  , 227.4359441 , 398.380694  , 168.3623578 ,
       194.3913964 , 334.8785903 , 220.8933269 , 276.9539523 ,
       256.6576629 , 228.8266268 , 263.4305032 , 220.486294  ,
       246.7577856 , 201.6063617 , 333.955669  , 217.2387971 ,
       144.4433504 , 417.9094699 , 415.0308225 , 543.8037651 ,
       604.3300406 , 451.9662153 , 458.5136857 , 439.5246578 ,
       513.2528925 , 164.7348144 , 188.4534392 , 280.789792  ,
       170.979218  , 195.083761  , 281.6564387 , 238.7485806 ,
       240.6600475 , 186.5509056 , 207.0508685 , 313.4451122 ,
       307.8810955 , 306.3028792 , 305.9685272 , 306.7737112 ,
       211.7292498 , 214.4797357 , 229.0448493 , 249.0768168 ,
       319.9961838 , 127.1387607 , 274.6675915 , 212.0815988 ,
       452.9029364 , 438.4681593 , 406.9967654 , 402.7573754 ,
       474.6420701 , 433.7538408 , 457.116799  , 551.5241219 ,
       389.19218   , 375.086675  , 349.5662663 , 334.8587333 ,
       409.9578508 , 426.5322004 , 274.110415  , 153.8602799 ,
       227.3942027 , 188.1657579 , 178.0757343 , 259.2489612 ,
       225.1320256 , 430.3352046 , 344.0675019 , 349.8762614 ,
       323.2937053 , 331.2626534 , 322.5365938 , 339.5925977 ,
       316.7584397 , 369.941785  , 321.2568991 , 316.9557675 ,
       195.5686316 , 149.5953655 , 221.1768194 , 204.4033192 ,
       188.5628229 , 187.3070624 , 222.6475623 , 277.358006  ,
       258.1220947 , 299.7632164 , 276.5616817 , 232.7485186 ,
       278.3352238 , 345.4926811 , 279.651294  , 304.8700741 ,
       262.5683139 , 306.2380068 , 278.9729032 , 228.0476693 ,
       264.5846126 , 165.6341217 , 189.4032599 , 167.8930793 ,
       224.2681767 , 167.9191414 , 184.7952057 , 310.3378408 ,
       167.4971887 , 254.8412194 , 259.3194742 , 248.3119136 ,
       246.1182292 , 249.397525  , 264.5188551 , 263.1044146 ,
       242.9929239 , 247.0532157 , 256.4313213 , 338.4916996 ,
       204.3392388 , 298.9327309 , 225.7948208 , 210.3802716 ,
       214.1150148 , 126.6453077 , 237.4612292 , 339.5755419 ,
       272.8793539 , 238.5461393 , 334.7237021 , 267.1205868 ,
       263.9008622 , 237.5197315 , 356.2593427 , 193.9917327 ,
       172.4184614 , 169.1210271 , 176.6474186 , 211.862964  ,
       129.2863843 , 160.7509047 , 212.7612467 , 158.8655763 ,
       358.3372412 , 351.480923  , 349.3239688 , 416.2396774 ,
       332.8519985 , 361.1085995 , 372.2994397 , 360.0306287 ,
       353.2755063 , 364.4044841 , 362.0339118 , 357.7614495 ,
       345.7400253 , 481.4588636 , 358.9255368 , 325.0119948 ,
       373.6120376 , 333.4126934 , 300.9164934 , 328.8078188 ,
       254.9848533 , 233.5301455 , 269.3174487 , 247.8548194 ,
       395.9751274 , 214.0689448 , 286.0188934 , 222.2660299 ,
       297.8239872 , 276.0449014 , 335.5572068 , 262.6987819 ,
       299.9353746 , 273.9498621 , 311.9204426 , 422.5302788 ,
       380.573741  , 390.583132  , 326.8958461 , 333.2602912 ,
       361.8603169 , 374.9604627 , 363.9187669 , 341.4607615 ,
       327.2759718 , 368.9474426 , 372.7780203 , 264.9928116 ,
       302.3039563 , 282.1171082 , 308.8704865 , 301.8994855 ,
       262.8074004 , 285.8673722 , 230.9585208 , 184.2385268 ,
       159.987316  , 232.577565  , 165.2671224 , 201.8561899 ,
       161.6078893 , 181.8288324 , 186.9054888 , 274.8484737 ])

In [3]:
import numpy as np
from tensorflow import keras

In [7]:
model = keras.Sequential()
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dense(10, activation='softmax'))

model.compile(optimizer=keras.optimizers.RMSprop(0.01),
              loss=keras.losses.CategoricalCrossentropy(),
              metrics=[keras.metrics.CategoricalAccuracy()])

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

model.fit(data, labels, epochs=10)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - categorical_accuracy: 0.0949 - loss: 79.8863
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.0999 - loss: 571.1974
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.0934 - loss: 1329.3440
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.1048 - loss: 2186.9163
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.1046 - loss: 3377.7593
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.1161 - loss: 4653.1299
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.1175 - loss: 6161.4512
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.1129 - loss: 8191.4087
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.0831 - loss: 10478.5361
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.0807 - loss: 13112.1094

In [13]:
model.evaluate(data, labels)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.0881 - loss: 17606.6777

[17622.923828125, 0.10999999940395355]

In [39]:
import tensorflow as tf
from scipy import stats

In [5]:
class BinaryTruePositives(tf.keras.metrics.Metric):

    def __init__(self, name='binary_true_positives', **kwargs):
        super(BinaryTruePositives, self).__init__(name=name, **kwargs)
        self.true_positives = self.add_weight(name='tp', initializer='zeros')

    def update_state(self, y_true, y_pred, sample_weight=None):
        y_true = tf.cast(y_true, tf.bool)
        y_pred = tf.cast(y_pred, tf.bool)

        values = tf.logical_and(tf.equal(y_true, True), tf.equal(y_pred, True))
        values = tf.cast(values, self.dtype)
        if sample_weight is not None:
            sample_weight = tf.cast(sample_weight, self.dtype)
            values = tf.multiply(values, sample_weight)
        self.true_positives.assign_add(tf.reduce_sum(values))

    def result(self):
        return self.true_positives

    def reset_states(self):
        self.true_positives.assign(0)

m = BinaryTruePositives()
m.update_state([0, 1, 1, 1], [0, 1, 0, 0])
print('Intermediate result:', float(m.result()))

m.update_state([1, 1, 1, 1], [0, 1, 1, 0])
print('Final result:', float(m.result()))

Intermediate result: 1.0
Final result: 3.0

In [17]:
print('m.true_positives:', float(m.true_positives))

m.true_positives: 3.0

In [8]:
risk_load = 1.2
init_weal = 388.6
subs_coef = 0.5
co_alpha = 0.008
prem_upper = 500
prem_buff = 495
penalty_coef = 1e-6

In [19]:
class Metric_penalty(keras.metrics.Metric):
    """
    This class measures the penalty to a certain NN model, if its corresponding insurance
    premium is out of the accepted range of policyholder.
    """
    def __init__(self, risk_load, prem_upper, prem_buff, name='metric_penalty', **kwargs):
        super(Metric_penalty, self).__init__(name=name, **kwargs)
        self.risk_load = risk_load
        self.prem_upper = prem_upper
        self.prem_buff = prem_buff

        self.total = self.add_weight(name='total', initializer='zeros')

    def update_state(self, y_true, y_pred, sample_weight=None):
        temp0 = tf.reduce_mean(y_pred)
        self.total.assign_add(tf.reduce_mean(temp0))
    
    def result(self):
        temp1 = self.risk_load * self.total
        temp2 = tf.maximum(temp1 - self.prem_upper, 0)
        temp3 = tf.square(temp2)
        temp4 = tf.minimum(temp1 - self.prem_buff, 0)
        temp5 = tf.square(temp4)
        temp6 = temp3 + temp5 # Penalty term
        return temp6
    
    def reset_states(self):
        return self.total.assign(0)

In [42]:
class tilted_loss_2(keras.losses.Loss):
    """
    This function defines a customized loss function based on Value at Risk 95%.
    """
    def __init__(self, var_level, risk_load, init_weal, subs_coef, prem_upper, prem_buff, penalty_coef, name='tilted_loss2', **kwargs):
        super(tilted_loss_2, self).__init__(name=name, **kwargs)
        self.var_level = var_level
        self.risk_load = risk_load
        self.init_weal = init_weal
        self.subs_coef = subs_coef
        self.prem_upper = prem_upper
        self.prem_buff = prem_buff
        self.penalty_coef = penalty_coef

    def call(self, y_true, y_pred):
        """
        This function will conduct once a tilted_loss instance is built.\n
        And this function gives the tilted_loss2 function.
        """
        phi_inverse = stats.norm.ppf(self.var_level)
    
        temp2 = self.risk_load * tf.reduce_mean(y_pred)
        w = self.init_weal - y_true + y_pred - self.subs_coef * temp2
        temp10 = tf.reduce_mean(w)
        temp11 = tf.reduce_mean(tf.pow(w - temp10, 3)) / tf.pow(tf.reduce_mean(tf.pow(w - temp10, 2)), 3/2)
        temp12 = tf.reduce_mean(tf.pow(w - temp10, 4)) / tf.pow(tf.reduce_mean(tf.pow(w - temp10, 2)), 2) - 3
        temp13 = phi_inverse + (phi_inverse ** 2 - 1) * temp11 / 6\
              + (phi_inverse ** 3 - 3 * phi_inverse) * temp12 / 24\
             - (2 * phi_inverse ** 3 - 5 * phi_inverse) * tf.pow(temp11, 2) / 36
        temp22 = temp10 + temp13 * tf.pow(tf.reduce_mean(tf.pow(w - temp10, 2)), 1/2)
        temp1 = -temp22
        temp14 = tf.reduce_mean(tf.maximum(y_pred - y_true - 100, 0)) * 1e3  # To ensure indemnity cannot exceed loss
        temp3 = tf.maximum(temp2 - self.prem_upper, 0)
        temp4 = tf.square(temp3)
        temp5 = tf.minimum(temp2 - self.prem_buff, 0)
        temp6 = tf.square(temp5)
        temp7 = temp1 + self.penalty_coef * temp4 + self.penalty_coef * temp6 + self.penalty_coef * temp14
        return temp7

In [40]:
class Metric_premium(keras.metrics.Metric):
    """
    This class estimates the corresponding insurance premium of a certain NN model.
    """
    def __init__(self, risk_load, name='metric_premium', **kwargs):
        super(Metric_premium, self).__init__(name=name, **kwargs)
        self.risk_load = risk_load
        
        self.total = self.add_weight(name='total', initializer='zeros')

    def update_state(self, y_true, y_pred, sample_weight=None):
        temp1 = tf.reduce_mean(y_pred)
        self.total.assign_add(tf.reduce_mean(temp1))

    def result(self):
        return self.risk_load * self.total
    
    def reset_states(self):
        return self.total.assign(0)

In [25]:
metric_utility = Metric_premium(risk_load)
metric_utility.update_state(np.array([1,2,3,4,5,6]), np.array([1,3,5,2,6,4]))
print('Intermediate result:', float(metric_utility.result()))

Intermediate result: 3.6000001430511475

In [43]:
model = keras.Sequential()
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dense(10, activation='softmax'))

model.compile(optimizer=keras.optimizers.RMSprop(0.01),
              loss=tilted_loss_2(0.05, risk_load, init_weal, subs_coef, prem_upper, prem_buff, penalty_coef),
              metrics=[Metric_penalty(risk_load, prem_upper, prem_buff),
                       Metric_premium(risk_load)])

data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

model.fit(data, labels, epochs=10)

Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: -387.4078 - metric_penalty: 243014.4375 - metric_premium: 2.0364
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: -387.4115 - metric_penalty: 243014.4375 - metric_premium: 2.0364
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: -387.4175 - metric_penalty: 243014.4375 - metric_premium: 2.0364
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: -387.4123 - metric_penalty: 243014.4375 - metric_premium: 2.0364
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: -387.4200 - metric_penalty: 243014.4375 - metric_premium: 2.0364
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: -387.4143 - metric_penalty: 243014.4375 - metric_premium: 2.0364
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: -387.4135 - metric_penalty: 243014.4375 - metric_premium: 2.0364
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: -387.4176 - metric_penalty: 243014.4375 - metric_premium: 2.0364
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: -387.4178 - metric_penalty: 243014.4375 - metric_premium: 2.0364
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: -387.4182 - metric_penalty: 243014.4375 - metric_premium: 2.0364